author: eccentric_nz
description: Add the ability to dye water in cauldrons
main: me.eccentric_nz.dyeablewater.DyeableWater
name: DyeableWater
load: POSTWORLD
version: 1.0.6
api-version: 1.16
permissions:
  dyeablewater.use:
    description: Allow a player to dye water in a cauldron.
    default: op
  dyeablewater.lava:
    description: Allow a player to place lava in a cauldron and destroy items thrown into it.
    default: op
  dyeablewater.brew:
    description: Allow a player to brew potions in a cauldron.
    default: op
